spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
#    ddl-auto:create 新建表示用
#  none,create,create-drop
      ddl-auto: update
      show-sql: true